default: &default
  docker:
    - image: cimg/node:18.3.0
  working_directory: ~/project

install-pnpm: &install-pnpm
  - run:
      name: "Install pnpm"
      command: "npm i -g pnpm"

install-packages: &install-packages
  - node/install-packages:
      cache-path: ~/project/node_modules
      override-ci-command: pnpm install

version: 2.1

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Build"
          command: "pnpm build"

  tests:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Tests"
          command: "pnpm test"

  eslint:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "ESlint"
          command: "pnpm lint"

  typecheck:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "TypeCheck"
          command: "pnpm typecheck"

  prettier:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Prettier"
          command: "pnpm format:check"

  release:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: Set registry URL
          command: npm set registry https://npm.pkg.github.com
      - run:
          name: Authenticate with registry
          command:
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_AUTH_TOKEN" >
            ~/project/.npmrc echo "enable-pre-post-scripts=true" ?
            ~/project/.npmrc
      - run:
          name: "Build package"
          command: "pnpm build"
      - run:
          name: "Release"
          command: "pnpm release"

orbs:
  node: circleci/node@5.0.3
workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - typecheck
      - prettier
      - release:
          requires:
            - build
            - tests
            - eslint
            - typecheck
            - prettier
          filters:
            branches:
              only:
                - master
