default: &default
  docker:
    - image: cimg/base:stable
  working_directory: ~/project

version: 2.1
orbs:
  node: circleci/node@18.3.0
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Build"
          command: "pnpm build"
  tests:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Tests"
          command: "pnpm test"
  eslint:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "ESlint"
          command: "pnpm lint"
  typecheck:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "TypeCheck"
          command: "pnpm typecheck"
  prettier:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Prettier"
          command: "pnpm prettier:check"

workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - typecheck
      - prettier
