default: &default
  docker:
    - image: cimg/node:18.3.0
  working_directory: ~/project

version: 2.1

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Build"
          command: "pnpm build"

  tests:
    <<: *default
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Tests"
          command: "pnpm test"

  eslint:
    <<: *default
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "ESlint"
          command: "pnpm lint"

  typecheck:
    <<: *default
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "TypeCheck"
          command: "pnpm typecheck"

  prettier:
    <<: *default
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "npm i -g pnpm"
      - run:
          name: "Prettier"
          command: "pnpm prettier:check"

orbs:
  node: circleci/node@5.0.3
workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - typecheck
      - prettier
