default: &default
  docker:
    - image: circleci/node:18.3.0
  working_directory: ~/project

restore_cache: &restore_cahce
  restore_cache:
    name: "Restore pnpm Package Cache"
    keys:
      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

pnpm: &pnpm
  run:
    name: "Install pnpm package manager"
    command: |
      sudo corepack enable && corepack prepare  --activate pnpm@7.11.0
save_cache: &save_cache
  save_cache:
    name: "Save pnpm Package Cache"
    key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
    paths:
      - node_modules

install_dep: &install_dep
  run:
    name: Install Dependencies
    command: |
      pnpm install

version: 2.1

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - <<: *restore_cahce
      - <<: *pnpm
      - <<: *install_dep
      - <<: *save_cache
      - run:
          name: "Build"
          command: "pnpm build"
  tests:
    <<: *default
    steps:
      - checkout
      - <<: *restore_cahce
      - <<: *pnpm
      - <<: *install_dep
      - <<: *save_cache
      - run:
          name: "Tests"
          command: "pnpm test"
  eslint:
    <<: *default
    steps:
      - checkout
      - <<: *restore_cahce
      - <<: *pnpm
      - <<: *install_dep
      - <<: *save_cache
      - run:
          name: "ESlint"
          command: "pnpm lint"
  typecheck:
    <<: *default
    steps:
      - checkout
      - <<: *restore_cahce
      - <<: *pnpm
      - <<: *install_dep
      - <<: *save_cache
      - run:
          name: "TypeCheck"
          command: "pnpm typecheck"
  prettier:
    <<: *default
    steps:
      - checkout
      - <<: *restore_cahce
      - <<: *pnpm
      - <<: *install_dep
      - <<: *save_cache
      - run:
          name: "Prettier"
          command: "pnpm prettier:check"

workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - typecheck
      - prettier
