default: &default
  docker:
    - image: cimg/node:18.3.0
  working_directory: ~/project

install-pnpm: &install-pnpm
  - run:
      name: "Install pnpm"
      command: "npm i -g pnpm"

install-packages: &install-packages
  - node/install-packages:
      cache-path: ~/project/node_modules
      override-ci-command: pnpm install

version: 2.1

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Build"
          command: "pnpm build"

  tests:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Tests"
          command: "pnpm test"

  eslint:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "ESlint"
          command: "pnpm lint"

  typecheck:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "TypeCheck"
          command: "pnpm typecheck"

  prettier:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: "Prettier"
          command: "pnpm format:check"

orbs:
  node: circleci/node@5.0.3
workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - typecheck
      - prettier
